CREATE TABLE "UM_SPAN_USER_POSITION" (
    "SPAN_KPPN" VARCHAR2(150 BYTE) NOT NULL,
    "POSITION_NAME" VARCHAR2(240 BYTE) NOT NULL,
    "USER_ID" NUMBER NOT NULL,
    "ENABLED_FLAG" VARCHAR2(1 BYTE) NOT NULL,
    CONSTRAINT "UM_SPAN_USER_POSITION_UK1" UNIQUE ( "POSITION_NAME" )
)
;
