MERGE INTO UM_SPAN_USER_POSITION SAKTI USING (
SELECT NVL(SPAN.POSITION_NAME, SAKTI.POSITION_NAME) POSITION_NAME
    ,  NVL(SPAN.SPAN_KPPN, SAKTI.SPAN_KPPN) SPAN_KPPN
    ,  NVL(SPAN.USER_ID, SAKTI.USER_ID) USER_ID
    ,  NVL2(SPAN.POSITION_NAME, 'Y', 'N') ENABLED_FLAG
FROM (
    SELECT SUBSTR(PAP.NAME,1,3) SPAN_KPPN
        , FU.USER_ID
        , PAP.NAME              POSITION_NAME
    FROM   FND_USER@SPAN_PROD                    FU
          ,HR.PER_ALL_ASSIGNMENTS_F@SPAN_PROD    PAA
          ,HR.PER_ALL_POSITIONS@SPAN_PROD        PAP
          ,HR.PER_ALL_PEOPLE_F@SPAN_PROD         PAF
          ,FND_RESPONSIBILITY_VL@SPAN_PROD       R
          ,FND_USER_RESP_GROUPS_DIRECT@SPAN_PROD RG
    WHERE  PAA.PERSON_ID(+) = PAF.PERSON_ID
    AND    PAA.POSITION_ID = PAP.POSITION_ID(+)
    AND    PAF.PERSON_ID(+) = FU.EMPLOYEE_ID
    AND    RG.RESPONSIBILITY_ID = R.RESPONSIBILITY_ID(+)
    AND    FU.USER_ID = RG.USER_ID(+)
    AND RG.START_DATE <= SYSDATE AND NVL(RG.END_DATE, SYSDATE + 1) > SYSDATE -- ACTIVE RESPONSIBILITY
    AND FU.START_DATE <= SYSDATE AND NVL(FU.END_DATE, SYSDATE + 1) > SYSDATE -- ACTIVE USER
    AND REGEXP_LIKE(R.RESPONSIBILITY_NAME, '^[0-9]{3,3}_PM_UNGGAH_RT$') -- RESPONSIBILITY: <KPPN>_PM_UNGGAH_RT
    AND REGEXP_LIKE(PAP.NAME, '^[0-9]{3,3}\.000000\.FO PD\.') -- RESPONSIBILITY PUNYA KPPN ( BUKAN SATKER )
    AND SUBSTR(R.RESPONSIBILITY_NAME,1,3) = SUBSTR(PAP.NAME,1,3) -- KPPN POSITION = KPPN RESPONSIBILITY
    ) SPAN FULL OUTER JOIN UM_SPAN_USER_POSITION SAKTI 
        ON SPAN.POSITION_NAME = SAKTI.POSITION_NAME
) SPAN_SAKTI ON (SPAN_SAKTI.POSITION_NAME = SAKTI.POSITION_NAME)
WHEN MATCHED THEN
    UPDATE SET SAKTI.SPAN_KPPN = SPAN_SAKTI.SPAN_KPPN
             , SAKTI.USER_ID = SPAN_SAKTI.USER_ID
             , SAKTI.ENABLED_FLAG = SPAN_SAKTI.ENABLED_FLAG
WHEN NOT MATCHED THEN
    INSERT (SPAN_KPPN, POSITION_NAME, USER_ID, ENABLED_FLAG)
    VALUES (SPAN_SAKTI.SPAN_KPPN, SPAN_SAKTI.POSITION_NAME, SPAN_SAKTI.USER_ID, SPAN_SAKTI.ENABLED_FLAG)
;
